### PR TITLE
Add Asynchronous Comment & Likes Viewing + Comment Pinning on Windows Machines

### PR DESCRIPTION
**Pull request by JRoy**
# Windows:
The script now opens two windows. The main window/script will display output (comments/likes & general console output), while the secondary script/window will be the command line.
# Linux/macOS:
The script will now run in legacy mode on these operating systems. Legacy mode is basically what the script is as of v0.4. So there will be no comment/likes view and you will only have the commands provided to you that were in 0.4. I have no plans to backport new commands to the legacy system but I intend to keep supporting it and add any new backend changes I make.
# Download/Test This Beta:
To download & install this beta please follow these directions:

1. [Click here](https://github.com/JRoy/InstagramLive-PHP/releases/tag/0.5-BETA-3) to download the latest "Source Code (zip)". (Beta 3 as of 8/21/18)
2. Unzip this to a new folder and re-run the `composer install` command.
3. Run your goLive.php script as normal. (`php goLive.php`)
4. Please leave any bugs/feedback in this thread!

# This Pull Request:
If anyone has a Windows machine and would like to test this code please leave your feedback here.

As of now, this pull is **not** ready to merge and more changes will follow.

Thanks,
Josh

### CODE REVIEW

**Comment by AnitaPazhohesh** [comment]
Hi Josh,

Where can I download the updated version? Please send me the link.
should I replace the previous files of your php script on my Windows PC
with this updated version to get the new feature or there are any other
process?

**Comment by JRoy** [comment]
@AnitaPazhohesh: The first v0.5 Beta Release is located here: [https://github.com/JRoy/InstagramLive-PHP/releases/tag/0.5-BETA-1](https://github.com/JRoy/InstagramLive-PHP/releases/tag/0.5-BETA-1)

To install this beta, download the source zip at the link above and install it like you were installing it for the first time. (Skip downloading/installing php and composer if you already did that)

Please leave any feedback here!

**Comment by AnitaPazhohesh** [comment]
Thanks Josh, great job.
Anita

**Comment by penteseter123** [comment]
Eror This Pinned instagram how to show my comments instagram not my friends or other 

screenshot_54

**Comment by JRoy** [comment]
@penteseter123: You are pasting the entire comment, you need the comment id. I have yet to even test pinning myself and was not aware that comment id's are not showing. I will atempt to fix this.

**Comment by penteseter123** [comment]
@JRoy  Thanks for the Fast Respon yes fixing got get ID Comentar

**Comment by JRoy** [comment]
Beta 2 has been released; Changes include fixing the comment ids, and pin and unpin commands

[Download Here](https://github.com/JRoy/InstagramLive-PHP/releases/tag/0.5-BETA-2)

**Comment by JRoy** [comment]
@penteseter123 Let me know if comment id's show now and if comment pinning works.

**Comment by penteseter123** [comment]
Sorry Your Code Beta 2 not show pin code because not show command pin this
code versi 0.4
https://github.com/JRoy/InstagramLive-PHP/releases/tag/0.5-BETA-2

**Comment by JRoy** [comment]
@pentester123 this command is windows only and the command is handled in commandLine.php

**Comment by penteseter123** [comment]
can it be packaged first like beta 1 which already has an addition, so we
just have to download it without coding modifications again

**Comment by JRoy** [comment]
It is packaged the same way

**Comment by penteseter123** [comment]
[image: image.png]

Show Pinned Success  but the comments that are displayed are only the
viewers who comment if I want to comment on myself how it needs to develop
coding again thank you best regards

**Comment by JRoy** [comment]
@pentester123 check #21 ;)

**Comment by penteseter123** [comment]
[image: image.png]

I did not find the code or command to display pinned for my comments and
where I wrote my comment thank you for the quick response

**Comment by JRoy** [comment]
I can add a command to view the pinned command

**Comment by penteseter123** [comment]
*Ok I am ready to test and ready to wait for comments for myself ...*
*for comments from other people who want to be pinned already*

**Comment by JRoy** [comment]
@penteseter123: Can you please send me a screenshot of comments showing in the command window so I can verify it works

**Comment by penteseter123** [comment]
to display pinned success but pinned is displayed robbyhermawan64 what if
the one who made my own pinned comment is albahjah_tangerang which in my
opinion should have development

# This is just an example of the testing I did

**Comment by penteseter123** [comment]
[image: Screenshot_58.png]
to display pinned success but pinned is displayed robbyhermawan64 what if
the one who made my own pinned comment is albahjah_tangerang which in my
opinion should have development

# This is just an example of the testing I did

**Comment by JRoy** [comment]
No issues were reported/found while testing **this** feature. Merging into the 0.5 branch so we can add s'more features with the new async stuff 😄!

**Pull request merged**
